apps/blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from apps.blog.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView

app_name = 'blog'

urlpatterns = [
    # blog urls
    path('add_post/', PostCreateView.as_view(), name='add_post'),
    path('blog/', PostListView.as_view(), name='blog'),
    path('post/<int:pk>', cache_page(60)(PostDetailView.as_view()), name='post'),
    path('post/update/<int:pk>', PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),
]

apps/mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from apps.mailings.views import MailCreateView, MailListView, MailDeleteView, MailUpdateView, MailingsCreateView, \
    MailingsListView, MailingsUpdateView, MailingsDeleteView, MailingLogListView, HomePageView

app_name = 'mailings'

urlpatterns = [
    path('', cache_page(60)(HomePageView.as_view()), name='home'),
    # mails urls
    path('add_mail/', MailCreateView.as_view(), name='add_mail'),
    path('mails/', MailListView.as_view(), name='mails'),
    path('mail/update/<int:pk>', MailUpdateView.as_view(), name='mail_update'),
    path('mail/delete/<int:pk>', MailDeleteView.as_view(), name='mail_delete'),

    # mailings urls
    path('add_mailing/', MailingsCreateView.as_view(), name='add_mailing'),
    path('mailings/', MailingsListView.as_view(), name='mailings'),
    path('mailing/update/<int:pk>', MailingsUpdateView.as_view(), name='mailings_update'),
    path('mailing/delete/<int:pk>', MailingsDeleteView.as_view(), name='mailings_delete'),

    # logs urls
    path('logs', MailingLogListView.as_view(), name='logs'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('apps.clients.urls'), name='clients'),
    path('', include('apps.mailings.urls'), name='mailings'),
    path('users/', include('apps.users.urls'), name='users'),
    path('blog/', include('apps.blog.urls'), name='blog'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from django.utils.text import slugify

NULLABLE = {'blank': True, 'null': True}

class Post(models.Model):
    post_title = models.CharField(max_length=250, verbose_name='Post Title')
    text = models.TextField(verbose_name='Text', **NULLABLE)
    preview = models.ImageField(upload_to='blog/', verbose_name='Preview', **NULLABLE)
    published_date = models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')
    is_published = models.BooleanField(default=True, verbose_name='Published')
    views = models.IntegerField(default=0, verbose_name='Views')

    def delete(self, *args, **kwargs):
        if self.is_published:
            self.is_published = False
        self.save()

    def __str__(self):
        return f'{self.post_title}'

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'

apps/mailings/models.py
from django.db import models

from apps.clients.models import Groups, Clients
from apps.users.models import User

NULLABLE = {'blank': True, 'null': True}


class Mail(models.Model):
    subject = models.CharField(max_length=500, verbose_name='Subject of the e-mail')
    body = models.TextField(verbose_name='Body of the e-mail')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE)

    class Meta:
        verbose_name = 'mail'
        verbose_name_plural = 'mails'


class Mailings(models.Model):
    FREQUENCY_CHOICES = (
        ('D', 'daily'),
        ('W', 'weekly'),
        ('M', 'monthly')
    )
    STATUS_CHOICES = (
        ('created', 'created'),
        ('running', 'running'),
        ('completed', 'completed'),
    )

    time = models.DateTimeField(**NULLABLE, verbose_name='Time of sending')
    end_time = models.DateTimeField(**NULLABLE, verbose_name='Time of the ending')
    frequency = models.CharField(max_length=10, choices=FREQUENCY_CHOICES, verbose_name='Frequency of sending')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='created',
                              verbose_name='Status of sending')
    clients = models.ForeignKey(Groups, on_delete=models.CASCADE, verbose_name='Group of clients')
    text = models.ForeignKey(Mail, on_delete=models.CASCADE, verbose_name='Text of mailing')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f'{self.time}, {self.frequency}, {self.status}, {self.clients}'

    class Meta:
        verbose_name = 'mailing'
        verbose_name_plural = 'mailings'
        ordering = ('-time',)


class MailingLog(models.Model):
    ATTEMPT_STATUS_CHOICES = (
        ('success', 'success'),
        ('failure', 'failure'),
    )

    attempt_date = models.DateTimeField(auto_now_add=True, verbose_name='Date of the last attempt')
    attempt_status = models.CharField(max_length=10, choices=ATTEMPT_STATUS_CHOICES,
                                      verbose_name='Status of the last attempt')
    response = models.TextField(**NULLABLE, verbose_name='Response of the server')
    mailing = models.ForeignKey(Mailings, default=None, on_delete=models.CASCADE, **NULLABLE, verbose_name='Mailing')

    class Meta:
        verbose_name = 'log'
        verbose_name_plural = 'logs'
        ordering = ('-attempt_date',)

apps/mailings/forms.py
from django import forms

from apps.mailings.models import Mail, Mailings


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control-10'


class MailForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mail
        fields = '__all__'
        exclude = ('owner',)


class MailingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailings
        fields = '__all__'
        exclude = ('status', 'owner',)

apps/mailings/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView, TemplateView

from apps.blog.models import Post
from apps.clients.models import Clients
from apps.mailings.forms import MailForm, MailingsForm
from apps.mailings.models import Mail, Mailings, MailingLog
from apps.mailings.services import send_mailing


class HomePageView(TemplateView):
    template_name = 'mailings/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['count_mailings_all'] = Mailings.objects.all().count()
        context_data['count_mailings_active'] = Mailings.objects.filter(status__in=['created', 'running']).count()
        context_data['count_clients'] = Clients.objects.distinct().count()
        context_data['blog'] = Post.objects.filter(is_published=True).order_by('?')[:3]
        return context_data
class MailCreateView(LoginRequiredMixin, CreateView):
    model = Mail
    form_class = MailForm
    success_url = reverse_lazy('mailings:mails')

    def form_valid(self, form):
        """Adds owner of the mail"""
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailListView(LoginRequiredMixin, ListView):
    model = Mail
    extra_context = {
        'title': 'Your Mails'
    }

    def get_queryset(self):
        """Sort by pk, filter by owner"""
        queryset = super().get_queryset()
        if not self.request.user.is_superuser:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mail
    form_class = MailForm
    success_url = reverse_lazy('mailings:mails')

    def test_func(self):
        return self.request.user == self.get_object().owner


class MailDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Mail
    success_url = reverse_lazy('mailings:mails')

    def test_func(self):
        return self.request.user == self.get_object().owner


class MailingsCreateView(LoginRequiredMixin, CreateView):
    model = Mailings
    form_class = MailingsForm
    success_url = reverse_lazy('mailings:mailings')

    def form_valid(self, form):
        """Adds owner of the mail, sends the first email"""
        self.object = form.save()
        self.object.owner = self.request.user
        send_mailing()
        self.object.save()
        return super().form_valid(form)


class MailingsListView(LoginRequiredMixin, ListView):
    model = Mailings
    extra_context = {
        'title': 'Your Mailings'
    }

    def get_queryset(self):
        """Sort by pk, filter by owner"""
        queryset = super().get_queryset()
        if not self.request.user.is_superuser:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailingsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mailings
    form_class = MailingsForm
    success_url = reverse_lazy('mailings:mailings')

    def test_func(self):
        return self.request.user == self.get_object().owner

    def form_valid(self, form):
        """Adds owner of the mail"""
        self.object = form.save()
        send_mailing()
        self.object.save()
        return super().form_valid(form)


class MailingsDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Mailings
    success_url = reverse_lazy('mailings:mailings')

    def test_func(self):
        return self.request.user == self.get_object().owner


class MailingLogListView(LoginRequiredMixin, ListView):
    model = MailingLog
    extra_context = {
        'title': 'Your History of Mailing'
    }

    def get_queryset(self):
        """Sort by pk, filter ny owner of the mail"""
        queryset = super().get_queryset()
        if not self.request.user.is_superuser:
            mailing = Mailings.objects.filter(owner=self.request.user)
            mailing_pk = [mail.pk for mail in mailing]
            # __in in mailing__in filter by list of data
            queryset = queryset.filter(mailing__in=mailing_pk)
        return queryset

apps/mailings/templates/mailings/home.html
{% extends 'clients/base.html' %}

{% load my_tags %}

{% block content %}
    <body>
    <div class="container-h text-center my-5 py-5">
        <div class="row">
            <div class="col-md-10 mx-auto">
                <div class="card mb-4 box-shadow">
                    <h1 class="font-weight-normal">Mailing service</h1>
                    <div class="card-body text-muted">
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>All our mailings : {{ count_mailings_all }}</li>
                            <li>Active mailings : {{ count_mailings_active }}</li>
                            <li>Clients to send : {{ count_clients }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        {% for post in blog %}
            <div class="col">
                <div class="card shadow-sm">
                    {% if object.preview %}
                        <img class="card-img-top"
                             src="{{ post.preview|mediapath }}"
                             alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                        <p class="card-text">{{ post.post_title|title }}</p>
                        <p class="card-text">{{ post.text|truncatechars:100 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a type="button" class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'blog:post' post.pk %}">View</a>
                                {% if perms.blog.change_post %}
                                    <a type="button" class="btn btn-sm btn-outline-secondary"
                                       href="{% url 'blog:post_update' post.pk %}">Edit</a>
                                {% endif %}
                                {% if perms.blog.delete_post %}
                                    <a type="button" class="btn btn-sm btn-outline-secondary"
                                       href="{% url 'blog:post_delete' post.pk %}">Delete</a>
                                {% endif %}
                            </div>
                            <small class="text-body-secondary">{{ post.published_date }}</small>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </body>
{% endblock %}

apps/mailings/templates/mailings/mail_confirm_delete.html
{% extends 'clients/base.html' %}

{% block content %}
    <form method="post">
        <section class="content-section">
            <h1>Removal of mail {{ object.subject }}</h1>

            <div class="alert alert-danger">
                <p>Are you sure? </p>
            </div>
            {% csrf_token %}
            <a href="{% url 'mailings:mails' %}" class="btn btn-default">No, it was a rash decision.</a>
            <input type="submit" value="Yes, delete the mail." class="btn btn-danger"/>

        </section>
    </form>
{% endblock %}

apps/mailings/templates/mailings/mail_form.html
{% extends 'clients/base.html' %}


{% block content %}
    <form enctype="multipart/form-data" method="post" id="product_form" novalidate>
        <div class="row flex-wrap">
            <div class="col-md-6">
                <div class="card">

                    {% csrf_token %}
                    {{ form.as_p }}

                    <button class="w-100 btn btn-lg btn-primary" type="submit">Save</button>

                </div>
            </div>
        </div>
    </form>


{% endblock %}

apps/mailings/templates/mailings/mail_list.html
{% extends 'clients/base.html' %}

{% block content %}
    {% for object in object_list %}
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <p class="card-text">{{ object.subject }}</p>
                    <p class="card-text">{{ object.body }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a type="button" class="btn btn-sm btn-outline-secondary"
                               href="{% url 'mailings:mail_update' object.pk %}">Edit</a>

                            <a type="button" class="btn btn-sm btn-outline-secondary"
                               href="{% url 'mailings:mail_delete' object.pk %}">Delete</a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <a type="button" class="btn btn-sm btn-outline-secondary"
       href="{% url 'mailings:add_mail' %}">Create a new mail</a>
{% endblock %}

apps/mailings/templates/mailings/mailinglog_list.html
{% extends 'clients/base.html' %}

{% block content %}
    <div class="table-responsive small">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Attempt Date</th>
                <th scope="col">Status</th>
                <th scope="col">Response</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td><a href="#" class="nav-link">{{ object.pk }}</a></td>
                    <td>{{ object.attempt_date }}</td>
                    <td>{{ object.attempt_status }}</td>
                    <td>{{ object.response }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

apps/mailings/templates/mailings/mailings_confirm_delete.html
{% extends 'clients/base.html' %}

{% block content %}
    <form method="post">
        <section class="content-section">
            <h1>Removal of mailing</h1>

            <div class="alert alert-danger">
                <p>Are you sure? </p>
            </div>
            {% csrf_token %}
            <a href="{% url 'mailings:mailings' %}" class="btn btn-default">No, it was a rash decision.</a>
            <input type="submit" value="Yes, delete the mailing." class="btn btn-danger"/>

        </section>
    </form>
{% endblock %}

apps/mailings/templates/mailings/mailings_form.html
{% extends 'clients/base.html' %}


{% block content %}
    <form enctype="multipart/form-data" method="post" id="product_form" novalidate>
        <div class="row flex-wrap">
            <div class="col-md-6">
                <div class="card">

                    {% csrf_token %}
                    {{ form.as_p }}

                    <button class="w-100 btn btn-lg btn-primary" type="submit">Save</button>

                </div>
            </div>
        </div>
    </form>


{% endblock %}

apps/mailings/templates/mailings/mailings_list.html
{% extends 'clients/base.html' %}

{% block content %}
    <div class="table-responsive small">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Time of sending</th>
                <th scope="col">Frequency</th>
                <th scope="col">Status</th>
                <th scope="col">Clients</th>
                <th scope="col">Texts</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td><a href="#" class="nav-link">{{ object.pk }}</a></td>
                    <td>{{ object.time }}</td>
                    <td>{{ object.frequency }}</td>
                    <td>{{ object.status }}</td>
                    <td>{{ object.clients.group_name }}</td>
                    <td>{{ object.text.subject }}</td>
                    <td><a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:mailings_update' object.pk %}">Edit</a></td>
                    <td><a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:mailings_delete' object.pk %}">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a type="button" class="btn btn-sm btn-outline-secondary"
           href="{% url 'mailings:add_mailing' %}">Create new mailing</a>
    </div>

{% endblock %}