apps/blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from apps.blog.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView

app_name = 'blog'

urlpatterns = [
    # blog urls
    path('add_post/', PostCreateView.as_view(), name='add_post'),
    path('blog/', PostListView.as_view(), name='blog'),
    path('post/<int:pk>', cache_page(60)(PostDetailView.as_view()), name='post'),
    path('post/update/<int:pk>', PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),
]

apps/clients/urls.py
from django.urls import path

from apps.clients.views import ClientsCreateView, ClientsListView, ClientsUpdateView, ClientsDetailView, \
    ClientsDeleteView, GroupsCreateView, GroupsListView, GroupsUpdateView, GroupsDeleteView

app_name = 'clients'

urlpatterns = [
    # clients urls
    path('add_client/', ClientsCreateView.as_view(), name='add_client'),
    path('<int:pk>/clients/', ClientsListView.as_view(), name='clients_list'),
    path('client/<int:pk>', ClientsDetailView.as_view(), name='client_detail'),
    path('client/update/<int:pk>', ClientsUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>', ClientsDeleteView.as_view(), name='client_delete'),

    # groups urls
    path('add_group/', GroupsCreateView.as_view(), name='add_group'),
    path('groups/', GroupsListView.as_view(), name='groups_list'),
    path('groups/update/<int:pk>', GroupsUpdateView.as_view(), name='groups_update'),
    path('groups/delete/<int:pk>', GroupsDeleteView.as_view(), name='groups_delete'),

]

apps/mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from apps.mailings.views import MailCreateView, MailListView, MailDeleteView, MailUpdateView, MailingsCreateView, \
    MailingsListView, MailingsUpdateView, MailingsDeleteView, MailingLogListView, HomePageView

app_name = 'mailings'

urlpatterns = [
    path('', cache_page(60)(HomePageView.as_view()), name='home'),
    # mails urls
    path('add_mail/', MailCreateView.as_view(), name='add_mail'),
    path('mails/', MailListView.as_view(), name='mails'),
    path('mail/update/<int:pk>', MailUpdateView.as_view(), name='mail_update'),
    path('mail/delete/<int:pk>', MailDeleteView.as_view(), name='mail_delete'),

    # mailings urls
    path('add_mailing/', MailingsCreateView.as_view(), name='add_mailing'),
    path('mailings/', MailingsListView.as_view(), name='mailings'),
    path('mailing/update/<int:pk>', MailingsUpdateView.as_view(), name='mailings_update'),
    path('mailing/delete/<int:pk>', MailingsDeleteView.as_view(), name='mailings_delete'),

    # logs urls
    path('logs', MailingLogListView.as_view(), name='logs'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('apps.clients.urls'), name='clients'),
    path('', include('apps.mailings.urls'), name='mailings'),
    path('users/', include('apps.users.urls'), name='users'),
    path('blog/', include('apps.blog.urls'), name='blog'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/clients/models.py
from django.db import models

from apps.users.models import User

NULLABLE = {'blank': True, 'null': True}

class Groups(models.Model):
    group_name = models.CharField(max_length=250, verbose_name='Group Name')
    description = models.TextField(verbose_name='Description', **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE, related_name='+')

    def __str__(self):
        return f'{self.group_name}'

    class Meta:
        verbose_name = 'group'
        verbose_name_plural = 'groups'

class Clients(models.Model):
    email = models.EmailField(unique=True, verbose_name='Email')
    name = models.CharField(max_length=250, verbose_name='Name')
    comment = models.TextField(**NULLABLE)
    group = models.ForeignKey(Groups, on_delete=models.PROTECT, verbose_name='Group')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f'{self.email} {self.name}'

    class Meta:
        verbose_name = 'client'
        verbose_name_plural = 'clients'

apps/clients/forms.py
from django import forms

from apps.clients.models import Clients, Groups


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control-10'


class ClientsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Clients
        fields = '__all__'
        exclude = ('owner', )


class GroupsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Groups
        fields = '__all__'
        exclude = ('owner',)

apps/clients/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView

from apps.clients.forms import GroupsForm, ClientsForm
from apps.clients.models import Clients, Groups


# CRUD
class ClientsCreateView(LoginRequiredMixin, CreateView):
    model = Clients
    form_class = ClientsForm
    success_url = reverse_lazy('clients:groups_list')

    def form_valid(self, form):
        """Adds owner of the client"""
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientsListView(LoginRequiredMixin, ListView):
    model = Clients

    def get_queryset(self):
        """Sort by pk, filter by owner"""
        queryset = super().get_queryset().filter(group_id=self.kwargs.get('pk')).order_by('pk')
        if not self.request.user.is_superuser:
            queryset = queryset.filter(owner=self.request.user)
        return queryset

    def get_context_data(self, *args, **kwargs):
        """Add group name to context data"""
        context_data = super().get_context_data(**kwargs)
        groups = Groups.objects.get(pk=self.kwargs.get('pk'))
        context_data['title'] = f'Clients from the group {groups.group_name}'
        return context_data


class ClientsDetailView(LoginRequiredMixin, DetailView):
    model = Clients
    template_name = 'clients/clients_detail.html'

    def get_queryset(self):
        """Sort by pk, filter by owner"""
        queryset = super().get_queryset()
        if not self.request.user.is_superuser:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class ClientsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Clients
    form_class = ClientsForm
    success_url = reverse_lazy('clients:groups_list')

    def test_func(self):
        return self.request.user == self.get_object().owner


class ClientsDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Clients
    success_url = reverse_lazy('clients:groups_list')

    def test_func(self):
        return self.request.user == self.get_object().owner


class GroupsCreateView(LoginRequiredMixin, CreateView):
    model = Groups
    form_class = GroupsForm
    success_url = reverse_lazy('clients:groups_list')

    def form_valid(self, form):
        """Add owner to group"""
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class GroupsListView(LoginRequiredMixin, ListView):
    model = Groups
    extra_context = {
        'title': 'Your Groups'
    }

    def get_queryset(self):
        """Sort by pk, filter by owner"""
        queryset = super().get_queryset()
        if not self.request.user.is_superuser:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class GroupsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Groups
    form_class = GroupsForm
    success_url = reverse_lazy('clients:groups_list')

    def test_func(self):
        return self.request.user == self.get_object().owner


class GroupsDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Groups
    success_url = reverse_lazy('clients:groups_list')

    def test_func(self):
        return self.request.user == self.get_object().owner

apps/clients/templates/clients/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>{{ title }}</title>


    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


{% include 'clients/includes/inc_menu.html' %}

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{ title }}</h1>
                <p class="lead text-body-secondary">Automatic Mailing Service</p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            {% if user.is_authenticated %}
                <a href="{% url 'clients:add_group' %}">Create a new clients group</a>
                <a href="{% url 'mailings:add_mailing' %}">Create a new mailing list</a>
            {% endif %}
            {% if perms.blog.add_post %}
                <a href="{% url 'blog:add_post' %}">Create a new post</a>
            {% endif %}
        </p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.js' %}"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>

</body>
</html>

apps/clients/templates/clients/client_form.html
{% extends 'clients/base.html' %}


{% block content %}
    <form enctype="multipart/form-data" method="post" id="product_form" novalidate>
        {% csrf_token %}
        <div>
            <label for="email">E-mail</label>
            <input id="email" type="email" name="email" class="form-control" value="{{ object.email }}"
                   required>
        </div>
        <div>
            <label for="first_name">First name/Company name</label>
            <input id="first_name" type="text" name="first_name" class="form-control" value="{{ object.first_name }}"
                   required>
        </div>
        <div>
            <label for="last_name">Last name (if required)</label>
            <input id="last_name" type="text" name="last_name" class="form-control" value="{{ object.last_name }}">
        </div>
        <div>
            <label for="comment">Comment</label>
            <textarea name="comment" rows="3" class="form-control jsCountCharacters"
                      id="comment">{{ object.comment }}</textarea>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Save</button>

        {% if object %}
            <a type="button" href="#">Delete</a>
        {% endif %}
    </form>

{% endblock %}

apps/clients/templates/clients/clients_confirm_delete.html
{% extends 'clients/base.html' %}

{% block content %}
    <form method="post">
        <section class="content-section">
            <h1>Removal of client {{ object.name }}</h1>

            <div class="alert alert-danger">
                <p>Are you sure? </p>
            </div>
            {% csrf_token %}
            <a href="{% url 'clients:client_detail' object.pk %}" class="btn btn-default">No, it was a rash decision.</a>
            <input type="submit" value="Yes, delete the client." class="btn btn-danger"/>

        </section>
    </form>
{% endblock %}

apps/clients/templates/clients/clients_detail.html
{% extends 'clients/base.html' %}

{% block content %}
    <div class="col">
        <div class="card shadow-sm">
            <div class="card-body">
                <p class="card-text">{{ object.name|title }}, {{ object.email }}</p>
                <p class="card-text">{{ object.comment }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% if user == object.owner or user.is_superuser %}
                            <a type="button" class="btn btn-sm btn-outline-secondary"
                               href="{% url 'clients:client_update' object.pk %}">Edit</a>
                            <a type="button" class="btn btn-sm btn-outline-secondary"
                               href="{% url 'clients:client_delete' object.pk %}">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/clients/templates/clients/clients_form.html
{% extends 'clients/base.html' %}


{% block content %}
    <form enctype="multipart/form-data" method="post" id="product_form" novalidate>
        <div class="row flex-wrap">
            <div class="col-md-6">
                <div class="card">

                    {% csrf_token %}
                    {{ form.as_p }}

                    <button class="w-100 btn btn-lg btn-primary" type="submit">Save</button>

                </div>
            </div>
        </div>
    </form>


{% endblock %}

apps/clients/templates/clients/clients_list.html
{% extends 'clients/base.html' %}

{% block content %}
    <div class="table-responsive small">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">E-mail</th>
                <th scope="col">Name</th>
                <th scope="col">Comment</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td><a href="{% url 'clients:client_detail' object.pk %}" class="nav-link">{{ object.pk }}</a></td>
                    <td>{{ object.email }}</td>
                    <td>{{ object.name }}</td>
                    <td>{{ object.comment|truncatechars:100 }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a type="button" class="btn btn-sm btn-outline-secondary"
           href="{% url 'clients:add_client' %}">Create a new client</a>
    </div>

{% endblock %}

apps/clients/templates/clients/groups_confirm_delete.html
{% extends 'clients/base.html' %}

{% block content %}
    <form method="post">
        <section class="content-section">
            <h1>Removal of group {{ object.name }}</h1>

            <div class="alert alert-danger">
                <p>Are you sure? </p>
            </div>
            {% csrf_token %}
            <a href="{% url 'clients:groups_update' object.pk %}" class="btn btn-default">No, it was a rash decision.</a>
            <input type="submit" value="Yes, delete the group." class="btn btn-danger"/>

        </section>
    </form>
{% endblock %}

apps/clients/templates/clients/groups_form.html
{% extends 'clients/base.html' %}


{% block content %}
    <form enctype="multipart/form-data" method="post" id="product_form" novalidate>
        <div class="row flex-wrap">
            <div class="col-md-6">
                <div class="card">

                    {% csrf_token %}
                    {{ form.as_p }}

                    <button class="w-100 btn btn-lg btn-primary" type="submit">Save</button>

                </div>
            </div>
        </div>
    </form>

{% endblock %}

apps/clients/templates/clients/groups_list.html
{% extends 'clients/base.html' %}

{% block content %}
    {% for object in object_list %}
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <p class="card-text">{{ object.group_name|title }}</p>
                    <p class="card-text">{{ object.description|truncatechars:100 }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a type="button" class="btn btn-sm btn-outline-secondary"
                               href="{% url 'clients:clients_list' object.pk %}">View Clients</a>
                            {% if user == object.owner or user.is_superuser %}
                                <a type="button" class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'clients:groups_update' object.pk %}">Edit</a>

                                <a type="button" class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'clients:groups_delete' object.pk %}">Delete</a>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endfor %}
{% endblock %}